{
  "updates": [
    {
      "allow": [
        {
          "dependency-type": "all"
        }
      ],
      "directory": "/",
      "package-ecosystem": "docker",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "allow": [
        {
          "dependency-type": "all"
        }
      ],
      "directory": "/",
      "package-ecosystem": "github-actions",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "allow": [
        {
          "dependency-type": "all"
        }
      ],
      "directory": "/",
      "package-ecosystem": "uv",
      "schedule": {
        "interval": "daily"
      }
    }
  ],
  "version": 2
}