services:
  podcast-tools:
    image: ghcr.io/williamjacksn/podcast-tools
    init: true

  shell:
    image: ghcr.io/williamjacksn/podcast-tools
    init: true
    volumes:
      - ./:/home/python/podcast-tools
